-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS Kommentti CASCADE;
DROP TABLE IF EXISTS Ainesosa CASCADE;
DROP TABLE IF EXISTS Drinkki CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Liitostaulu CASCADE;




